# @package _group_
tag: default_210203
debug: False
load_data_from_pkl: 0
load_model: 0
input_model: 0
output_path: ???

defaults:
  - model: hierarchicalVAE
  - data: mnist
  - engine: divae_training
  - task